### ISSUE TITLE
`predIntNpar()` Exact method query

### ISSUE THREAD

**Issue by williamlai2** [alexkowa/EnvStats#25]
I have a question about `predIntNpar()` in EnvStats. 

[predIntNpar: Nonparametric Prediction Interval for a Continuous... in EnvStats: Package for Environmental Statistics, Including US EPA Guidance (rdrr.io)](https://rdrr.io/cran/EnvStats/man/predIntNpar.html)

[EnvStats/R/predIntNpar.R at master · cran/EnvStats (github.com)](https://github.com/cran/EnvStats/blob/master/R/predIntNpar.R)

The method in the output is ‘Exact’.

Is this the Dunnett Exact method as used in the other predInt functions, e.g. [predIntNormK: Compute the Value of K for a Prediction Interval for a Normal... in EnvStats: Package for Environmental Statistics, Including US EPA Guidance (rdrr.io)](https://rdrr.io/cran/EnvStats/man/predIntNormK.html) or is it something else?

I assume it is the same, but it is not noted.

**Comment by williamlai2** [comment]
Or is it Danziger and Davis (1964)? 

If so, should:

 `Prediction Interval Method:      Exact`

be changed?

**Comment by SteveMillard** [comment]
As per the help file, the confidence level is computed using Equation (8), which comes from Danziger and Davis (1964).

**Comment by williamlai2** [comment]
Thanks. So should the output be changed to reflect this?

**Comment by SteveMillard** [comment]
Sure, if you want to change “Exact” to something like “Exact (Danziger and Davis, 1964)” that’s fine with me. I think the reason I used the term “Exact“ is because Danziger and Davis figured out the way to compute what the exact probability is.Sincerely,—Steve M.On Jan 24, 2024, at 11:01 PM, William Lai ***@***.***> wrote:﻿
Thanks. So should the output be changed to reflect this?

**Comment by williamlai2** [comment]
Happy to leave it. I worked it out a while ago but just wanted to clarify it. Thanks
