### ISSUE TITLE
Error in enparCensored

### ISSUE THREAD

**Issue by alexkowa** [alexkowa/EnvStats#39]
From the vignette of NADA2: Line 535-541
```
data(Example1, package = "NADA2")
enparCensored(Example1$Arsenic, Example1$NDisTRUE, 
             ci=TRUE, ci.method="bootstrap", ci.type="upper",
               n.bootstraps=5000)
```

Error in r - m[-1] : non-numeric argument to binary operator

**Comment by alexkowa** [comment]
The problem is in enparCensored.bootstrap.ci.R and the call of enParCensored.km with too few not censored observations.  enParCensored.km fails with 1 to 3 not censored observations. So I can set this to <4 in line 19. What do you think @SteveMillard ?

**Comment by SteveMillard** [comment]
Hi Alex,Thanks for catching this.  I’m on vacation through tomorrow and will figure it out on Friday.Thanks again for all you do!!Sincerely,—Steve M.On Jul 17, 2024, at 12:03 AM, Alexander Kowarik ***@***.***> wrote:﻿
The problem is in enparCensored.bootstrap.ci.R and the call of enParCensored.km with too few not censored observations.  enParCensored.km fails with 1 to 3 not censored observations. So I can set this to <4 in line 19. What do you think @SteveMillard ?

**Comment by SteveMillard** [comment]
Hi @alexkowa ,  
I cannot reproduce your example exactly unless you set the value of the `seed `argument.  However, the problem was that the check for the number of unique non-censored values in the function `enparCensored.bootstrap.ci()` was not correct.  As far as I can tell, the minimum number can be 2, not 4.  

Also, the function `enparCensored.km()` needed to be fixed so that there are default values for the arguments `ci.type`, `conf.level`, `pivot.statistic`, and `ci.sample.size`, so that for cases where `ci=FALSE` (e.g., when the function is called from `enparCensored.bootstrap.ci`), these arguments would not need to be supplied.

I added updated versions of `enparCensored.km()` and `enparCensored.bootstrap.ci()` in my fork.  Let me know if there are still issues.  Thanks for your help!
