### ISSUE TITLE
eqnorm() does not return median at p = 0.5 - bug

### ISSUE THREAD

**Issue by countzero2323** [alexkowa/EnvStats#6]
Hi alexkowa,

I tried to calculate the p = 0.5 percentile via eqnorm() and eqnormCensored() but I only get the mean in return.
The code:
```R
library(EnvStats)
attach(EPA.09.Ex.21.1.aldicarb.df)

df <- as.data.frame(Aldicarb.ppb[Well == "Well.1"])
colnames(df) <- "col_1"

value_1 <- eqnorm(Aldicarb.ppb[Well == "Well.1"], p = 0.5, ci = TRUE,
       ci.type = "lower", conf.level = 0.99)$quantiles

value_2 <- eqnorm(df$col_1, p = 0.5)$quantiles

ref_value_1 <- median(df$col_1)

ref_value_2 <- quantile(df$col_1, .5)
```
gives me:
```
> value_1
Median 
  23.1 
> value_2
Median 
  23.1 
> ref_value_1
[1] 22.05
> ref_value_2
  50% 
22.05 
```
Is this faulty reasoning or a bug?

Thanks a lot for your time and work!

**Comment by alexkowa** [comment]
Hi,
this is not a bug, but desired behaviour. Quantiles are estimated from a normal distribution that is defined by an estimated mean and standard deviation. So for a normal distribution the median=mean.
See this paragraph in the documentation:
Quantiles are estimated by 1) estimating the mean and standard deviation parameters by calling enorm with method="mvue", and then 2) calling the function qnorm and using the estimated values for mean and standard deviation. This estimator of the p'th quantile is sometimes called the quasi-maximum likelihood estimator (qmle; Cohn et al., 1989) because if the maximum likelihood estimator of standard deviation were used in place of the minimum variaince unbiased one, then this estimator of the quantile would be the mle of the p'th quantile.

Internally qnorm is used and for 50% it just returns (as expected) the mean:
`qnorm(.5,mean=.34)`
